- name: Variable
  hosts: localhost
  vars:
    URL: vars.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: Print URL from tasks
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com

- name: variables from files
  hosts: localhost
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Register variables
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: output
    - name: Print Output of the command
      ansible.builtin.debug:
        msg: "{{ output }}"